### ISSUE TITLE
Screenshots or Demo available?

### ISSUE THREAD

**Issue by pmsteil** [Popesites/Magento-Quickorder#10]
Hello, 

Is there a demo of your code or screenshots available? thanks!

**Comment by amenk** [comment]
![Screenshot_Auswahl_006](https://user-images.githubusercontent.com/1087128/64033040-f1ba1280-cb4b-11e9-96e6-6fb7e93024b2.png)

This is a screenshot from one of the shops, developed by us.

**Comment by Popesites** [comment]
Closing as this is not really a problem with code, also @amenk delivered the screenshot so we have nothing left here.
