### ISSUE TITLE
Not adding to cart

### ISSUE THREAD

**Issue by hallandellon** [Popesites/Magento-Quickorder#16]
Hi! Nice work you did here. I'm testing your extension, but it's not adding product to cart. I'm trying it with luma template with sample data and adding configurable products and simple products too, but sometimes it doesn't add product to cart and sometimes do.  Do you know what is happening?

**Comment by netdrag** [comment]
The products are added to the cart, but the cart is not updated. in newer versions of magento you need to have a sections.xml that tells magento which sections of the page needed to be updated. 

create a sections.xml in this modules /etc/frontend/ folder with the following content:

`<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Customer:etc/sections.xsd">
    <action name="quickorder/order/place">
        <section name="cart"/>
    </action>
    <action name="quickorder/index/view">
        <section name="cart"/>
    </action>
</config>`

this tells the actions quickorder/index/view and quickorder/order/place should update the section cart. I am not sure both actions are required.

**Comment by hallandellon** [comment]
Thank you @netdrag. Now it's working in Magento 2.3.5-p1.
