### ISSUE TITLE
Please publish on packagist and tag

### ISSUE THREAD

**Issue by amenk** [Popesites/Magento-Quickorder#6]
Thanks :-)

If you need any help with this, I am happy to help.

**Comment by amenk** [comment]
are you interested :)

**Comment by Popesites** [comment]
Yes please, you can go ahead and help with this!

**Comment by Popesites** [comment]
Should have been created here: https://packagist.org/packages/popesites/module-quickorder

**Comment by Popesites** [comment]
Would you want to help manage this repository?

**Comment by amenk** [comment]
We probably finished with most of the adaptations needed now, but will continue making PRs whenever new things emerge.
